#!/bin/bash
# run cron job to create maps with DDRP (cohorts)
cd C:/Users/tmwepprich/Desktop/repo/Grevstad_etal_2021
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2010 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2010_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2010 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2010_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2011 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2011_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2011 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2011_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2012 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2012_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2012 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2012_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2013 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2013_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2013 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2013_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2014 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2014_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2014 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2014_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2015 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2015_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2015 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2015_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2016 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2016_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2016 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2016_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2017 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2017_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2017 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2017_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2018 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2018_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
# .code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2018 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2018_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284
.code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2019 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2019_Kyushu --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.1 --cp_sd 0.284
.code/04_DDRP_phenology_model.R --spp APH --forecast_data DAYMET --start_year 2019 --start_doy 1 --end_doy 365 --keep_leap 0 --region_param CONUSPLUS --exclusions_stressunits 0 --pems 0 --mapA 0 --mapE 0 --mapL 0 --mapP 0 --out_dir APH2_NA_2019_Hokkaido --out_option 0 --ncohort 6 --odd_gen_map 0 --do_photo 1 --cp_mean 14.7 --cp_sd 0.284